
attributes(global) subroutine CUF_MGD_grans_test()
    use MY_CUDA
    implicit none
    integer(4) :: idgod, n_disc, gr, metod, s1, s2, ss1, ss2, kdir, type, i
    real(8) :: time, dist, wc, dsl, dsp, dsc, aa, bb, cc, the
    real(8) :: POTOK(dev_num_param), distant(3), Gran_normal(3), square, rast(3)
    real(8) :: qqq1(dev_num_param), qqq2(dev_num_param), qqq11(dev_num_param), qqq22(dev_num_param)
    real(8) :: qqq1_TVD(dev_num_param), qqq2_TVD(dev_num_param)
    real(8) :: df1, df2, dff1, dff2, rad1, rad2, rad3, rad4, rad5, gran_centr(3), cell_centr_s1(3)
    real(8) :: cell_centr_s2(3), cell_centr_ss1(3), cell_centr_ss2(3)
    logical :: tvd 

    tvd = .TRUE.

	kdir = 0
	idgod = 0
	n_disc = 0!! 1
	time = 100000.0
	gr = blockDim%x * (blockIdx%x - 1) + threadIdx%x   ! Номер потока

    if (gr > dev_N_gran) return

    type = dev_Gran_type(gr)

    if(type == 2) return

    POTOK = 0.0
	! s1 = dev_Gran_neighbour(1, gr)
	! s2 = dev_Gran_neighbour(2, gr)
    ! cell_centr_s1 = dev_Cell_center(:, s1)
    ! gran_centr = dev_Gran_center(:, gr)
    ! qqq1 = dev_Cell_par(:, s1)

    ! if(type == 3) then
    !     qqq2 = qqq1
    !     cell_centr_s2 = cell_centr_s1
    !     tvd = .FALSE.
    ! else
    !     qqq2 = dev_Cell_par(:, s2)
    !     cell_centr_s2 = dev_Cell_center(:, s2)
    ! end if

    ! ss1 = dev_Gran_neighbour_TVD(1, gr)
	! ss2 = dev_Gran_neighbour_TVD(2, gr)

    ! if(ss1 > 0 .and. ss2 > 0 .and. type == 1) then
    !     qqq11 = dev_Cell_par(:, ss1)
    !     qqq22 = dev_Cell_par(:, ss2)
    ! else
    !     qqq11 = qqq1
    !     qqq22 = qqq2
    ! end if


    ! distant = gran_centr - cell_centr_s1
	! dist = dev_norm2(distant)

end subroutine CUF_MGD_grans_test


attributes(global) subroutine CUF_MGD_grans(now)
    use MY_CUDA
    implicit none
	integer, intent(in) :: now
    integer(4) :: n_disc, gr, metod, s1, s2, ss1, ss2, type, i
    real(8) :: time, dist, wc, dsl, dsp, dsc, aa, bb, cc, the, BR, BPHI, V1, V2, V3, BTHE
    real(8) :: POTOK(dev_num_param), distant(3), Gran_normal(3), square, rast(3)
    real(8) :: qqq1(dev_num_param), qqq2(dev_num_param), qqq11(dev_num_param), qqq22(dev_num_param)
    real(8) :: qqq1_TVD(dev_num_param), qqq2_TVD(dev_num_param)
    real(8) :: df1, df2, dff1, dff2, rad1, rad2, rad3, rad4, rad5, gran_centr(3), cell_centr_s1(3)
    real(8) :: cell_centr_s2(3), cell_centr_ss1(3), cell_centr_ss2(3), mv, mb, r_rotate(3), b_phi, drot
    logical :: tvd 
    real(8) :: alpha, vvv(3), M1, M2, M11, M22


    tvd = .TRUE.
    metod = 0!3

    ! if(now == 1) then
    !     tvd = .FALSE.
    !     metod = 0
    ! end if

	n_disc = 0!! 1
	time = 100000.0
	gr = blockDim%x * (blockIdx%x - 1) + threadIdx%x   ! Номер потока

    if (gr > dev_N_gran) return

    type = dev_Gran_type(gr)

    !if(type == 2) return

 
    POTOK = 0.0
	s1 = dev_Gran_neighbour(1, gr)
	s2 = dev_Gran_neighbour(2, gr)

    cell_centr_s1 = dev_Cell_center(:, s1)

    gran_centr = dev_Gran_center(:, gr)
    distant = gran_centr - cell_centr_s1
	dist = dev_norm2(distant)
    rad5 = dev_norm2(gran_centr)

    ! if(rad5 < 70.0 .and. gran_centr(1) > 0 .and. sqrt(gran_centr(2)**2 + gran_centr(3)**2) < 15.0) then ! 120
    !     metod = 3
    ! else 
    if(rad5 < 150.0) then   ! .and. gran_centr(1) > 0
        metod = 3 
    end if

    !metod = 3

    if(s1 < 1) then
        print*, "s1 < 1"
        STOP
    end if

    qqq1 = dev_Cell_par(:, s1)

    if(qqq1(1) <= 0.0) then
        print*, "ERROR 9iu3498h34fh", qqq1(1), s1
        STOP
    end if

    Gran_normal = dev_Gran_normal(:, gr)

    if(type == 3) then
        cell_centr_s2 = cell_centr_s1
        tvd = .FALSE.

        if (Gran_normal(1) < 0.9) then
            if(qqq1(2) > -10.0) qqq1(2) = -10.0
        end if

        if (dabs(Gran_normal(1)) < 0.1) then
            qqq1(1) = 1.0
            qqq1(2) = -1.0
            qqq1(3) = 0.0
            qqq1(4) = 0.0
            qqq1(5) = 0.200304
            qqq1(6) = 0.420186 * cos(0.785398)
            qqq1(7) = 0.420186 * sin(0.785398)
            qqq1(8) = 0.0
        end if

        qqq2 = qqq1
    else if(type == 2) then
        return
        tvd = .FALSE.
        the = acos(gran_centr(3) / rad5)
        BR = -0.248585 * (3.00503 / rad5)**2
        BPHI = -0.2 * BR * sin(the) * (rad5 / 3.00503)
        BTHE = 0.0_8
        call dekard_skorost(gran_centr(3), gran_centr(1), gran_centr(2), BR, BPHI, BTHE, V3, V1, V2)

        mV = 66.6667

        ! dev_time_all
        qqq1(1) = 0.0249164 * (3.00503 / rad5)**2 * (1.0 + 0.5 * sin(2.0 * par_pi_8 * dev_time_all/0.03))
        qqq1(5) = 2.65775 * (3.00503 / rad5)**(2 * ggg)

        !print*, qqq1(1), sin(2.0 * par_pi_8 * dev_time_all/0.03)

        qqq1(2) = mV * gran_centr(1) / rad5
        qqq1(3) = mV * gran_centr(2) / rad5
        qqq1(4) = mV * gran_centr(3) / rad5

        qqq1(6) = V1
        qqq1(7) = V2
        qqq1(8) = V3
        qqq2 = qqq1
    else if(type == 4) then
        return
    else
        qqq2 = dev_Cell_par(:, s2)
        cell_centr_s2 = dev_Cell_center(:, s2)
    end if

    if(rad5 < 150.0) then 
        ! if(qqq1(1)/qqq2(1) > 5.0 .or. qqq1(1)/qqq2(1) < 0.2) metod = 1
        ! if(qqq1(1)/qqq2(1) > 5.0 .or. qqq1(1)/qqq2(1) < 0.2) then
        if(qqq1(1)/qqq2(1) > 20.0 .or. qqq1(1)/qqq2(1) < 0.05) then
            metod = 1
        ! else if(sqrt(qqq1(2)**2 + qqq1(3)**2 + qqq1(4)**2)/sqrt(ggg * qqq1(5)/qqq1(1)) > 1.0 .and. &
        !     sqrt(qqq2(2)**2 + qqq2(3)**2 + qqq2(4)**2)/sqrt(ggg * qqq2(5)/qqq2(1)) < 1.0) then
        !     metod = 1
        ! else if(sqrt(qqq1(2)**2 + qqq1(3)**2 + qqq1(4)**2)/sqrt(ggg * qqq1(5)/qqq1(1)) < 1.0 .and. &
        !     sqrt(qqq2(2)**2 + qqq2(3)**2 + qqq2(4)**2)/sqrt(ggg * qqq2(5)/qqq2(1)) > 1.0) then
        !     metod = 1
        end if
    end if

    M1 = sqrt(qqq1(2)**2 + qqq1(3)**2 + qqq1(4)**2)/sqrt(ggg * qqq1(5)/qqq1(1))
    M2 = sqrt(qqq2(2)**2 + qqq2(3)**2 + qqq2(4)**2)/sqrt(ggg * qqq2(5)/qqq2(1))
    if(gran_centr(1) < -60 .and. gran_centr(1) > -100 .and. M1 < 1.0 .and. M2 < 1.0 .and. &
        sqrt(gran_centr(2)**2 + gran_centr(3)**2) < 60.0 .and. dabs(Gran_normal(1)) < 0.1) then
        metod = 0
    end if

    !metod = 1 ! TODO: убрать
    
    square = dev_Gran_square(gr)

    !tvd = .FALSE.
    ! Делаем TVD и всякие сносы
    if(tvd == .TRUE.) then
        ss1 = dev_Gran_neighbour_TVD(1, gr)
	    ss2 = dev_Gran_neighbour_TVD(2, gr)

        if(ss1 > dev_N_cell .or. ss2 > dev_N_cell) then
            write(*, *) "ERROR"
            STOP
        end if


        if(ss1 > 0 .and. ss2 > 0 .and. type == 1) then
            cell_centr_ss1 = dev_Cell_center(:, ss1)
            cell_centr_ss2 = dev_Cell_center(:, ss2)
            rast = gran_centr - cell_centr_s1
            df1 = dev_norm2(rast)
            rast = gran_centr - cell_centr_s2
            df2 = dev_norm2(rast)
            rast = gran_centr - cell_centr_ss1
            dff1 = dev_norm2(rast)
            rast = gran_centr - cell_centr_ss2
            dff2 = dev_norm2(rast)
            qqq11 = dev_Cell_par(:, ss1)
            qqq22 = dev_Cell_par(:, ss2)


            M1 = sqrt(qqq1(2)**2 + qqq1(3)**2 + qqq1(4)**2)/sqrt(ggg * qqq1(5)/qqq1(1))
            M11 = sqrt(qqq11(2)**2 + qqq11(3)**2 + qqq11(4)**2)/sqrt(ggg * qqq11(5)/qqq11(1))
            M2 = sqrt(qqq2(2)**2 + qqq2(3)**2 + qqq2(4)**2)/sqrt(ggg * qqq2(5)/qqq2(1))
            M22 = sqrt(qqq22(2)**2 + qqq22(3)**2 + qqq22(4)**2)/sqrt(ggg * qqq22(5)/qqq22(1))

            ! В этом случае надо делать снос с градиентами и в сферической СК
            if(M1 > 5 .and. M11 > 5 .and. M2 > 5 .and. M22 > 5) then
            ! if(.False.) then

                rad1 = dev_norm2(cell_centr_s1)                              
                rad2 = dev_norm2(cell_centr_s2)                              
                rad3 = dev_norm2(cell_centr_ss1)                              
                rad4 = dev_norm2(cell_centr_ss2) 
                
                qqq1_TVD(1) = linear(-dff1, qqq11(1) * rad3**2, -df1, qqq1(1) * rad1**2, df2, qqq2(1) * rad2**2, 0.0_8)/ rad5**2
                qqq1_TVD(5) = linear(-dff1, qqq11(5) * rad3**(2 * ggg), -df1, qqq1(5) * rad1**(2 * ggg), df2,&
                    qqq2(5) * rad2**(2 * ggg), 0.0_8)/ rad5**(2 * ggg)
                
                qqq2_TVD(1) = linear(-dff2, qqq22(1) * rad4**2, -df2, qqq2(1) * rad2**2, df1, qqq1(1) * rad1**2, 0.0_8)/ rad5**2
                qqq2_TVD(5) = linear(-dff2, qqq22(5) * rad4**(2 * ggg), -df2, qqq2(5) * rad2**(2 * ggg), df1,&
                    qqq1(5) * rad1**(2 * ggg), 0.0_8)/ rad5**(2 * ggg)

                the = acos(gran_centr(3) / rad5);
                
                if(the > 3.14_8/9 .and. the < 8 * 3.14_8 / 9) then
                    ! Переводим скорости в сферическую с.к.
                    call spherical_skorost(cell_centr_s1(3), cell_centr_s1(1), cell_centr_s1(2), &
                        qqq1(4), qqq1(2), qqq1(3), aa, bb, cc)
                    qqq1(2) = aa
                    qqq1(3) = bb
                    qqq1(4) = cc
                    
                    call spherical_skorost(cell_centr_s2(3), cell_centr_s2(1), cell_centr_s2(2), &
                        qqq2(4), qqq2(2), qqq2(3), aa, bb, cc)
                    qqq2(2) = aa
                    qqq2(3) = bb
                    qqq2(4) = cc
                    
                    call spherical_skorost(cell_centr_ss1(3), cell_centr_ss1(1), cell_centr_ss1(2), &
                        qqq11(4), qqq11(2), qqq11(3), aa, bb, cc)
                    qqq11(2) = aa
                    qqq11(3) = bb
                    qqq11(4) = cc
                    
                    call spherical_skorost(cell_centr_ss2(3), cell_centr_ss2(1), cell_centr_ss2(2), &
                        qqq22(4), qqq22(2), qqq22(3), aa, bb, cc)
                    qqq22(2) = aa
                    qqq22(3) = bb
                    qqq22(4) = cc
                    
                    ! Перевод Магнитных полей в сферическую ск
                    
                    call spherical_skorost(cell_centr_s1(3), cell_centr_s1(1), cell_centr_s1(2), &
                        qqq1(8), qqq1(6), qqq1(7), aa, bb, cc)
                    qqq1(6) = aa
                    qqq1(7) = bb
                    qqq1(8) = cc
                    
                    call spherical_skorost(cell_centr_s2(3), cell_centr_s2(1), cell_centr_s2(2), &
                        qqq2(8), qqq2(6), qqq2(7), aa, bb, cc)
                    qqq2(6) = aa
                    qqq2(7) = bb
                    qqq2(8) = cc
                    
                    call spherical_skorost(cell_centr_ss1(3), cell_centr_ss1(1), cell_centr_ss1(2), &
                        qqq11(8), qqq11(6), qqq11(7), aa, bb, cc)
                    qqq11(6) = aa
                    qqq11(7) = bb
                    qqq11(8) = cc
                    
                    call spherical_skorost(cell_centr_ss2(3), cell_centr_ss2(1), cell_centr_ss2(2), &
                        qqq22(8), qqq22(6), qqq22(7), aa, bb, cc)
                    qqq22(6) = aa
                    qqq22(7) = bb
                    qqq22(8) = cc
                    
                    do i = 2, 4
                        qqq1_TVD(i) = linear(-dff1, qqq11(i), -df1, qqq1(i), df2, qqq2(i), 0.0_8)
                        qqq2_TVD(i) = linear(-dff2, qqq22(i), -df2, qqq2(i), df1, qqq1(i), 0.0_8)
                    end do
                    
                    do i = 6, 8
                        qqq1_TVD(i) = linear(-dff1, qqq11(i), -df1, qqq1(i), df2, qqq2(i), 0.0_8)
                        qqq2_TVD(i) = linear(-dff2, qqq22(i), -df2, qqq2(i), df1, qqq1(i), 0.0_8)
                    end do
                    
                    call dekard_skorost(gran_centr(3), gran_centr(1), gran_centr(2), &
                        qqq1_TVD(2), qqq1_TVD(3), qqq1_TVD(4), aa, bb, cc)
                    qqq1_TVD(4) = aa
                    qqq1_TVD(2) = bb
                    qqq1_TVD(3) = cc
                    call dekard_skorost(gran_centr(3), gran_centr(1), gran_centr(2), &
                        qqq2_TVD(2), qqq2_TVD(3), qqq2_TVD(4), aa, bb, cc)
                    qqq2_TVD(4) = aa
                    qqq2_TVD(2) = bb
                    qqq2_TVD(3) = cc
                    
                    call dekard_skorost(gran_centr(3), gran_centr(1), gran_centr(2), &
                        qqq1_TVD(6), qqq1_TVD(7), qqq1_TVD(8), aa, bb, cc)
                    qqq1_TVD(8) = aa
                    qqq1_TVD(6) = bb
                    qqq1_TVD(7) = cc
                    call dekard_skorost(gran_centr(3), gran_centr(1), gran_centr(2), &
                        qqq2_TVD(6), qqq2_TVD(7), qqq2_TVD(8), aa, bb, cc)
                    qqq2_TVD(8) = aa
                    qqq2_TVD(6) = bb
                    qqq2_TVD(7) = cc
                else
                    ! Переводим скорости в сферическую с.к.
                    call spherical_skorost(cell_centr_s1(1), cell_centr_s1(2), cell_centr_s1(3), &
                        qqq1(2), qqq1(3), qqq1(4), aa, bb, cc)
                    qqq1(2) = aa
                    qqq1(3) = bb
                    qqq1(4) = cc
                    
                    call spherical_skorost(cell_centr_s2(1), cell_centr_s2(2), cell_centr_s2(3), &
                        qqq2(2), qqq2(3), qqq2(4), aa, bb, cc)
                    qqq2(2) = aa
                    qqq2(3) = bb
                    qqq2(4) = cc
                    
                    call spherical_skorost(cell_centr_ss1(1), cell_centr_ss1(2), cell_centr_ss1(3), &
                        qqq11(2), qqq11(3), qqq11(4), aa, bb, cc)
                    qqq11(2) = aa
                    qqq11(3) = bb
                    qqq11(4) = cc
                    
                    call spherical_skorost(cell_centr_ss2(1), cell_centr_ss2(2), cell_centr_ss2(3), &
                        qqq22(2), qqq22(3), qqq22(4), aa, bb, cc)
                    qqq22(2) = aa
                    qqq22(3) = bb
                    qqq22(4) = cc
                    
                    ! Перевод Магнитных полей в сферическую ск
                    
                    call spherical_skorost(cell_centr_s1(1), cell_centr_s1(2), cell_centr_s1(3), &
                        qqq1(6), qqq1(7), qqq1(8), aa, bb, cc)
                    qqq1(6) = aa
                    qqq1(7) = bb
                    qqq1(8) = cc
                    
                    call spherical_skorost(cell_centr_s2(1), cell_centr_s2(2), cell_centr_s2(3), &
                        qqq2(6), qqq2(7), qqq2(8), aa, bb, cc)
                    qqq2(6) = aa
                    qqq2(7) = bb
                    qqq2(8) = cc
                    
                    call spherical_skorost(cell_centr_ss1(1), cell_centr_ss1(2), cell_centr_ss1(3), &
                        qqq11(6), qqq11(7), qqq11(8), aa, bb, cc)
                    qqq11(6) = aa
                    qqq11(7) = bb
                    qqq11(8) = cc
                    
                    call spherical_skorost(cell_centr_ss2(1), cell_centr_ss2(2), cell_centr_ss2(3), &
                        qqq22(6), qqq22(7), qqq22(8), aa, bb, cc)
                    qqq22(6) = aa
                    qqq22(7) = bb
                    qqq22(8) = cc
                    
                    do i = 2, 4
                        qqq1_TVD(i) = linear(-dff1, qqq11(i), -df1, qqq1(i), df2, qqq2(i), 0.0_8)
                        qqq2_TVD(i) = linear(-dff2, qqq22(i), -df2, qqq2(i), df1, qqq1(i), 0.0_8)
                    end do
                    
                    do i = 6, 8
                        qqq1_TVD(i) = linear(-dff1, qqq11(i), -df1, qqq1(i), df2, qqq2(i), 0.0_8)
                        qqq2_TVD(i) = linear(-dff2, qqq22(i), -df2, qqq2(i), df1, qqq1(i), 0.0_8)
                    end do
                    
                    call dekard_skorost(gran_centr(1), gran_centr(2), gran_centr(3), &
                        qqq1_TVD(2), qqq1_TVD(3), qqq1_TVD(4), aa, bb, cc)
                    qqq1_TVD(2) = aa
                    qqq1_TVD(3) = bb
                    qqq1_TVD(4) = cc
                    call dekard_skorost(gran_centr(1), gran_centr(2), gran_centr(3), &
                        qqq2_TVD(2), qqq2_TVD(3), qqq2_TVD(4), aa, bb, cc)
                    qqq2_TVD(2) = aa
                    qqq2_TVD(3) = bb
                    qqq2_TVD(4) = cc
                    
                    call dekard_skorost(gran_centr(1), gran_centr(2), gran_centr(3), &
                        qqq1_TVD(6), qqq1_TVD(7), qqq1_TVD(8), aa, bb, cc)
                    qqq1_TVD(6) = aa
                    qqq1_TVD(7) = bb
                    qqq1_TVD(8) = cc
                    call dekard_skorost(gran_centr(1), gran_centr(2), gran_centr(3), &
                        qqq2_TVD(6), qqq2_TVD(7), qqq2_TVD(8), aa, bb, cc)
                    qqq2_TVD(6) = aa
                    qqq2_TVD(7) = bb
                    qqq2_TVD(8) = cc
                end if
            else
                ! Обычный снос
                do i = 1, 8
                    qqq1_TVD(i) = linear(-dff1, qqq11(i), -df1, qqq1(i), df2, qqq2(i), 0.0_8)
                    qqq2_TVD(i) = linear(-dff2, qqq22(i), -df2, qqq2(i), df1, qqq1(i), 0.0_8)
                end do
            end if
        
            qqq1 = qqq1_TVD
            qqq2 = qqq2_TVD
        end if
    end if


    if(qqq1(1) < 0.0 .or. qqq2(1) < 0.0) then
        write(*, *) "Err1: ", qqq1(1), qqq1(2), qqq1(3), qqq1(4), qqq1(5), qqq1(6), qqq1(7), qqq1(8)
        write(*, *) "Err2: ",qqq2(1), qqq2(2), qqq2(3), qqq2(4), qqq2(5), qqq2(6), qqq2(7), qqq2(8)
        STOP
    end if

    wc = 0.0_8
    call chlld(metod, Gran_normal(1), Gran_normal(2), Gran_normal(3), &
	 	wc, qqq1, qqq2, &
         dsl, dsp, dsc,  &
         POTOK, n_disc)


    time = min(time, 0.3 * dist/(max(dabs(dsl), dabs(dsp)) + dabs(wc)) )   ! REDUCTION
    !time = min(time, 0.9 * dist/(dev_norm2(cross_product(gran_centr, rotate_velosity))))
	dev_Gran_POTOK(1:dev_num_param, gr) = POTOK * square
	
	dev_Gran_POTOK(dev_num_param + 1, gr) = 0.5 * DOT_PRODUCT(Gran_normal(:), qqq1(6:8) + qqq2(6:8)) * square

    if (.True.) then
        time = atomicmin(time_step2, time)   ! Атомарная операция взятия минимального значения
    end if

end subroutine  CUF_MGD_grans


attributes(global) subroutine CUF_MGD_cells(now)
    use MY_CUDA
    implicit none
	integer, intent(in) :: now

    integer(4) :: gr
	integer(4) :: st, i, j
	real(8) :: qqq(dev_num_param)  ! Переменные в ячейке
	real(8) :: dist, QQ3
	real(8) :: POTOK(dev_num_param), vv(3), rr(3), F(3)
	real(8) :: time, Volume, sks
	real(8) :: ro3, u3, v3, w3, p3, bx3, by3, bz3, T_K, mV, the, BR, BPHI, BTHE, VV3, VV1, VV2, dd
    real(8) :: rotate_velosity_lokal(3)
    real(8) :: Drotate_velosity_lokal(3)
    ! Задайте параметры цикла (единицы согласуйте с dev_time_all)
    real(kind=8), parameter :: t1 = 0.2_8    ! длительность первого интервала
    real(kind=8), parameter :: t2 = 0.01_8    ! длительность второго интервала
    real(kind=8), parameter :: dd1 = 1.0_8   ! значение dd на интервале t1
    real(kind=8), parameter :: dd2 = 100.0_8   ! значение dd на интервале t2
	real(kind=8) :: time_in_cycle, cycle_period
    
	gr = blockDim%x * (blockIdx%x - 1) + threadIdx%x   ! Номер потока
	time = time_step

    if (gr > dev_N_cell) return

    rotate_velosity_lokal = rotate_velosity
    Drotate_velosity_lokal = Drotate_velosity

    POTOK = 0.0
    sks = 0.0
    Volume = dev_Cell_Volume(gr)
    rr = dev_Cell_center(:, gr)
    dist = dev_norm2(rr)

    qqq = dev_Cell_par(:, gr)

    if(dist < 14.0) then
        the = acos(rr(3) / dist)
        !BR = -0.248585 * (2.30386 / dist)**2
        BR = -0.324242 * (2.30386 / dist)**2
        BPHI = -0.2 * BR * sin(the) * (dist / 2.30386)
        BTHE = 0.0_8
        call dekard_skorost(rr(3), rr(1), rr(2), BR, BPHI, BTHE, VV3, VV1, VV2)


        ! 0.08 - не прошли волны через AP
        ! 0.16
        !dd = (1.0 + 0.7 * sin(2.0 * par_pi_8 * dev_time_all/6.0))
        !dd = 1.0
        ! sin(2.0 * par_pi_8 * dev_time_all/0.1)

        ! Период полного цикла
        cycle_period = t1 + t2

        ! Вычисляем положение внутри текущего цикла
        time_in_cycle = mod(dev_time_all, cycle_period)

        ! Определяем dd в зависимости от того, на каком интервале находимся
        ! if (time_in_cycle < t1) then
        !     dd = dd1
        ! else
        !     dd = dd2
        ! end if

        ! if(sin(2.0 * par_pi_8 * dev_time_all/0.1) > 0.0) then
        !     dd = 1.3
        ! else
        !     dd = 1.0
        ! end if

        !dd = (1.0 + 0.7 * sin(2.0 * par_pi_8 * dev_time_all/6.0))
        dd = 1.0 !(1.0 + 0.5 * sin(2.0 * par_pi_8 * dev_time_all/0.3))

        mV = 86.9565! 66.6667

        ! dev_time_all
        !@ ro3 = 0.0249164 * (3.00503 / dist)**2 * dd ! / (dd**2)
        ro3 = 0.0249164 * (2.30386 / dist)**2 * dd ! / (dd**2)
        ! p3 = 2.65775 * (2.30386 / dist)**(2 * ggg)
        p3 = 4.52169 * (2.30386 / dist)**(2 * ggg)

        u3 = mV * rr(1) / dist
        v3 = mV * rr(2) / dist
        w3 = mV * rr(3) / dist

        bx3 = VV1
        by3 = VV2
        bz3 = VV3

        dev_Cell_par(:, gr) = (/ro3, u3, v3, w3, p3, bx3, by3, bz3/)
        return
    end if
    
    vv = qqq(2:4)
    !F = 2.0 * qqq(1) * cross_product(vv, rotate_velosity_lokal) + &
     !           qqq(1) * cross_product(rotate_velosity_lokal , cross_product(rr, rotate_velosity_lokal))  + &
    !            qqq(1) * cross_product(rr, Drotate_velosity_lokal) &
    !            - qqq(1) * rr * dev_GM / (dist**3)   
    !QQ3 = DOT_PRODUCT(F, vv);
    F = 0.0_8

    T_K = qqq(5) / qqq(1) * 39111.5 !66541.3
    QQ3 = qqq(1)**2 * 7.86113 * 1e21 * (-interpolate_cooling(T_K, dev_cooling_T, dev_cooling_Lambda, dev_cooling_lnT, dev_cooling_lnLambda) &
    + interpolate_cooling(T_K, dev_heating_T, dev_heating_Lambda, dev_heating_lnT, dev_heating_lnLambda)) ! 2.71588 * 1e21
    ! QQ3 = QQ3/100.0

    ! Просуммируем потоки через грани
    do i = 1, 6
        j = dev_Cell_gran(i, gr)
        if (j == 0) CYCLE
        if (j < 0) write(*, *) "ERROR 3876tfghjuyghejk"

        if (dev_Gran_neighbour(1, j) == gr) then
            POTOK = POTOK + dev_Gran_POTOK(1:dev_num_param, j)
            sks = sks + dev_Gran_POTOK(dev_num_param + 1, j)
        else
            POTOK = POTOK - dev_Gran_POTOK(1:dev_num_param, j)
            sks = sks - dev_Gran_POTOK(dev_num_param + 1, j)
        end if
    end do

    ro3 = qqq(1) - time * POTOK(1) / Volume
    
    if (ro3 <= 0.0_8) then
        write(*, *) " Ro < 0  3688 ---  ", ro3, qqq(1), rr(1), rr(2), rr(3)
        ro3 = 0.0001

        if(rr(1) > 0.0) then
            u3 = 0.0
            p3 = 1.0
        else
            u3 = -10.0
            p3 = 0.1 ! qqq(5)
        end if
        !u3 = -10.0! qqq(2)
        v3 = 0.0! qqq(3)
        w3 = 0.0! qqq(4)

        bx3 = qqq(6)
        by3 = qqq(7)
        bz3 = qqq(8)
    else
        u3 = (qqq(1) * qqq(2) - time * (POTOK(2) + (qqq(6)/cpi4) * sks) / Volume + time * F(1)) / ro3
        v3 = (qqq(1) * qqq(3) - time * (POTOK(3) + (qqq(7)/cpi4) * sks) / Volume + time * F(2)) / ro3
        w3 = (qqq(1) * qqq(4) - time * (POTOK(4) + (qqq(8)/cpi4) * sks) / Volume + time * F(3)) / ro3
        
        bx3 = qqq(6) - time * (POTOK(6) + qqq(2) * sks) / Volume
        by3 = qqq(7) - time * (POTOK(7) + qqq(3) * sks) / Volume
        bz3 = qqq(8) - time * (POTOK(8) + qqq(4) * sks) / Volume
        
        p3 = ((  ( qqq(5) / (ggg - 1.0) + 0.5 * qqq(1) * dev_norm2(qqq(2:4))**2 + (qqq(6)**2 + qqq(7)**2 + qqq(8)**2) / 25.13274122871834590768 ) &
            - time * ( POTOK(5) + (DOT_PRODUCT(qqq(2:4), qqq(6:8))/cpi4) * sks)/ Volume  + time * QQ3) - 0.5 * ro3 * (u3**2 + v3**2 + w3**2) - (bx3**2 + by3**2 + bz3**2) / 25.13274122871834590768 ) * (ggg - 1.0)
    end if



    
    if (p3 <= 0.0_8) then
        p3 = 0.0000001
    end if

    if( rr(1) < -70.0 .and. u3 > 0.0) u3 = -3.0_8

    dev_Cell_par(:, gr) = (/ro3, u3, v3, w3, p3, bx3, by3, bz3/)

end subroutine CUF_MGD_cells